In [1]:
import numpy as np

In [4]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b.shape)
print(b.size)
print(b.dtype)
print(b.ndim)

(2, 4)
8
int32
2


In [5]:
x=np.zeros([2,4],dtype=int)
x

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
x=np.ones([2,4],dtype=int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
x=np.random.random(4)
x

array([0.75453614, 0.39411579, 0.92450585, 0.11936332])

In [2]:
# copy in numpy
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [3]:
#view in numpy

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
# numpy Shape of array is the number of elements in each dimension.
# we use an attribute called shape
#2-D array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [5]:
#Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 
# and verify that last dimension has value 4:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [6]:
#Reshaping arrays
#Reshape From 1-D to 2-D

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Iterating Arrays 1-D
#Iterating means going through elements one by one.
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [12]:
#Iterating Arrays 2-D
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)
#iterating on each array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)
#iterating 3-D

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]
1
2
3
4
5
6
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [14]:
#iterating scalar for 3-D and using nditer() function
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)
#Iterating Array With Different Data Types
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

1
2
3
4
5
6
7
8
b'1'
b'2'
b'3'


In [15]:
#Enumerated Iteration Using ndenumerate()and 
# Iterating With Different Step Size

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)


(0,) 1
(1,) 2
(2,) 3
1
3
5
7


In [16]:
#Joining NumPy Arrays
#using concatenate() function
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)
#joining 2-D arrays along  rows 
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [22]:
#Joining NumPy Arrays
#using stack () function
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)
# stackking along rows we use hstack ()
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print("stacking along rows \n",arr)
#stacking along columns we use vstack()
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print("stacking along columns \n",arr)
#Stacking Along Height (depth)
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print("Stacking Along Height (depth) \n",arr)



[[1 4]
 [2 5]
 [3 6]]
stacking along rows 
 [1 2 3 4 5 6]
stacking along columns 
 [[1 2 3]
 [4 5 6]]
Stacking Along Height (depth) 
 [[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
#Splitting NumPy Arrays 
# Splitting is reverse operation of Joining.
# We use array_split() for splitting arrays
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 2)

print( "spliting in 2-arrays \n",newarr)
#Access the splitted arrays:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

spliting in 2-arrays [array([1, 2, 3]), array([4, 5, 6])]
[1 2]
[3 4]
[5 6]


In [1]:
import numpy as np
import time 
import sys